# Generated by Django 6.0.3 on 2026-03-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelCardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=200, verbose_name='ข้าพเจ้า')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อ-สกุล')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='สัญชาติ')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='หมู่โลหิต')),
                ('reg_address', models.TextField(blank=True, verbose_name='ที่อยู่ตามทะเบียนบ้าน')),
                ('reg_district', models.CharField(blank=True, max_length=200, verbose_name='อำเภอ/เขต/จังหวัด/รหัสไปรษณีย์')),
                ('use_reg_address', models.BooleanField(default=False, verbose_name='ใช้ที่อยู่ตามทะเบียนบ้าน')),
                ('contact_address', models.TextField(blank=True, verbose_name='ที่อยู่ที่สามารถติดต่อได้')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='โทรศัพท์')),
                ('id_card', models.CharField(blank=True, max_length=20, verbose_name='หมายเลขบัตรประชาชน')),
                ('department', models.CharField(blank=True, max_length=300, verbose_name='รับราชการ/หน่วยงาน')),
                ('old_card_number', models.CharField(blank=True, max_length=100, verbose_name='หมายเลขบัตรเดิม')),
                ('evidence', models.CharField(blank=True, max_length=300, verbose_name='หลักฐานประกอบ')),
                ('staff_types', models.JSONField(blank=True, default=list, null=True, verbose_name='ประเภทบุคลากร')),
                ('case_types', models.JSONField(blank=True, default=list, null=True, verbose_name='กรณี')),
                ('new_reasons', models.JSONField(blank=True, default=list, null=True, verbose_name='เหตุผลขอบัตรใหม่')),
                ('change_reasons', models.JSONField(blank=True, default=list, null=True, verbose_name='เหตุผลเปลี่ยนบัตร')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThaiAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdistrict', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=5)),
            ],
        ),
    ]
