# Generated by Django 6.0.1 on 2026-03-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='rh_factor',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Rh'),
        ),
    ]
