# Generated by Django 6.0.1 on 2026-03-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_personnelcardrequest_rh_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnelcardrequest',
            name='fullname',
        ),
        migrations.AddField(
            model_name='personnelcardrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personnelcardrequest',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
