# Generated by Django 6.0.1 on 2026-03-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_personnelcardrequest_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='case_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='change_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='new_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='staff_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
