# Generated by Django 6.0.1 on 2026-04-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_personnelcardrequest_case_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelcardrequest',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255, verbose_name='สังกัด'),
        ),
        migrations.AddField(
            model_name='personnelcardrequest',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='ตำแหน่ง'),
        ),
    ]
