# Generated by Django 6.0.1 on 2026-04-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_personnelcardrequest_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='change_reasons',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='new_reasons',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personnelcardrequest',
            name='staff_types',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
